version: 2
jobs:
  one:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:36:6d:4e:b4:e4:f5:e2:fa:ea:37:fb:13:d2:d3:da"
            - "77:c8:5e:67:2e:14:a6:1f:b6:ed:49:e0:dc:35:27:be"
      - checkout
      - run: 
          name: clone a remote repo
          command: |
            echo "Start clone..."
            git clone --verbose git@github.com:dcoughlin/mymemories.git
            echo hello >test.txt
            git add .
            git commit -m "mobile-pipeline"
  two:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  nightly:
     triggers:
       - schedule:
           cron: "27 2 * * *"
           filters:
             branches:
               only:
                 - master
                 - beta
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
