version: 2
jobs:
  one:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b3:36:6d:4e:b4:e4:f5:e2:fa:ea:37:fb:13:d2:d3:da"
      - run: 
          name: clone a remote repo
          command: |
            echo "Start clone..."
            git clone git@github.com:dcoughlin/mymemories.git
  two:
    docker:
       - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A more familiar hi"  
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: my_workspace

      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "Nope!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
          requires:
            - one
